// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Uy8C4QnktdxnKlpdFi21qJN0z_3LWNI',
    appId: '1:964150228916:ios:61540cabdad2ab42dfe4e1',
    messagingSenderId: '964150228916',
    projectId: 'fleetpay-b9f98',
    storageBucket: 'fleetpay-b9f98.appspot.com',
    iosBundleId: 'com.etteo.fleetPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXYddvyb-zlB8w7v5rOh7gEmO85OnI8Go',
    appId: '1:964150228916:web:f1824c2578e0d177dfe4e1',
    messagingSenderId: '964150228916',
    projectId: 'fleetpay-b9f98',
    authDomain: 'fleetpay-b9f98.firebaseapp.com',
    storageBucket: 'fleetpay-b9f98.appspot.com',
    measurementId: 'G-3EX8GBN41R',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXYddvyb-zlB8w7v5rOh7gEmO85OnI8Go',
    appId: '1:964150228916:web:f1824c2578e0d177dfe4e1',
    messagingSenderId: '964150228916',
    projectId: 'fleetpay-b9f98',
    authDomain: 'fleetpay-b9f98.firebaseapp.com',
    storageBucket: 'fleetpay-b9f98.appspot.com',
    measurementId: 'G-3EX8GBN41R',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Uy8C4QnktdxnKlpdFi21qJN0z_3LWNI',
    appId: '1:964150228916:ios:61540cabdad2ab42dfe4e1',
    messagingSenderId: '964150228916',
    projectId: 'fleetpay-b9f98',
    storageBucket: 'fleetpay-b9f98.appspot.com',
    iosBundleId: 'com.etteo.fleetPay',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUvXKh7SZdW3KEkbsYRAyHnSTVJmDpLys',
    appId: '1:964150228916:android:3641bf1f26a3adb9dfe4e1',
    messagingSenderId: '964150228916',
    projectId: 'fleetpay-b9f98',
    storageBucket: 'fleetpay-b9f98.appspot.com',
  );

}